# Generated by Django 6.0.4 on 2026-05-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainKDR', '0002_alter_documenttemplate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='template_type',
        ),
    ]
