# Generated by Django 6.0.4 on 2026-05-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainKDR', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Шаблон документа', 'verbose_name_plural': 'Шаблоны документов'},
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('blank', 'Пустой шаблон (для скачивания)'), ('variable', 'Шаблон с переменными (для генерации)')], default='variable', max_length=20, verbose_name='Тип шаблона'),
        ),
    ]
